### ISSUE TITLE
Question about correctness of Domain Accuracy

### ISSUE THREAD

**Issue by johanneszellinger** [val-iisc/SDAT#11]
Hello everybody, we are currently examining different DA method and tried to reproduce the SDAT paper results on our system. 
So far I have made two trainings with all the settings and arguments I could gather from the paper for DomainNET. The `val_acc` do look quite promising:

real->sketch:
![image](https://github.com/val-iisc/SDAT/assets/24492076/31f37449-5b7f-4a22-9f9f-fa01ac777f90)

sketch -> clipart
![image](https://github.com/val-iisc/SDAT/assets/24492076/0fd0d564-2c3d-403c-8312-5bf59a7c71bd)

However, the Domain accuracy is somewhat confusing for us (not smoothed):
real->sketch:
![image](https://github.com/val-iisc/SDAT/assets/24492076/5a6a8506-4b0f-4a96-b923-60e238e5abcb)

sketch -> clipart:
![image](https://github.com/val-iisc/SDAT/assets/24492076/a558efe1-d825-4524-b0bc-726f26c5e54d)

We would have expected a graph similar to this one from the paper for the Domain Accuracy:
![image](https://github.com/val-iisc/SDAT/assets/24492076/8d9403f9-660f-4e07-bdda-bd861d3a4092)

However, it seems this was done with the Homeoffice dataset and different settings. Question is now, can we assume that our results are correct?

**Comment by rangwani-harsh** [comment]
Thanks for your question.

The Domain accuracy fluctuates as it's adversarial training (i.e. discriminator will try to increase the domain accuracy, whereas the feature extractor will decrease it). 

In the DomainNet cases you have mentioned, you can observe the mean value of SDAT is similar to the plot provided by us. However, the fluctuations are function of dataset, hence can change with dataset and settings.

Hence, in my view the results produced by your experiments are correct in my opinion.

Thanks
Harsh

**Comment by johanneszellinger** [comment]
Perfect, thank you for the information. We where confused by the slight increase of the DA after the initial dip (better seen with a smoothed plot) - but with your explanation this makes more sense.
