### ISSUE TITLE
about domain acc

### ISSUE THREAD

**Issue by Xixi7301210** [val-iisc/SDAT#12]
Thanks for your sharing. I try to apply this method (cdan_sdat.py) to UDA  for an image regression task. But the domain acc keeps 100% with no decline. Can you give me some guidance?  Thanks a lot.

**Comment by rangwani-harsh** [comment]
Thanks for your interest in our work. We suggest you start with domain adaptive image regression work (like https://arxiv.org/pdf/2006.08251.pdf) and then apply SDAT to observe improvement. (see our README.MD on how to apply)

The method cdan_sdat.py is meant for classification tasks and might not be generalized well for image regression.
