### ISSUE TITLE
How to add SDAT on Object detection task？

### ISSUE THREAD

**Issue by 1184125805** [val-iisc/SDAT#9]
Is there any difference between classification task and Object detection task？

**Comment by rangwani-harsh** [comment]
Thanks for your interest in our work. We use the adversarial discriminator-based object detection method in the object detection task described in Sec. 6 and App. Sec. F.2 of our [paper](https://arxiv.org/pdf/2206.08213.pdf). We find that applying smooth loss (SAM) only on classification loss leads to optimal results.
